name       : haskell-http-conduit
version    : 2.2.3.1
release    : 1
source     :
    - http://hackage.haskell.org/package/http-conduit-2.2.3.1/http-conduit-2.2.3.1.tar.gz : 53ae16c601f980f323f2b24a32a776f9867b6b595e6e1929d440d1549715ca0e
license    : BSD-3-Clause
component  : programming.haskell
summary    : Provides for making efficient HTTP/HTTPS requests, providing either a simple or streaming interface.
description: |
    Provides for making efficient HTTP/HTTPS requests, providing either a simple or streaming interface.
builddeps  :
    - haskell-aeson
    - haskell-cabal-install
    - haskell-conduit-extra
    - haskell-http-client-tls
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
