name       : haskell-http-conduit
version    : 2.3.7.4
release    : 3
source     :
    - https://hackage.haskell.org/package/http-conduit-2.3.7.4/http-conduit-2.3.7.4.tar.gz : 6b7d66f4f0f567846a4d75f8345b708f0cc9afac14599ea3fb0fa4deab566ad5
license    : BSD-3-Clause
component  : programming.haskell
summary    : Provides for making efficient HTTP/HTTPS requests, providing either a simple or streaming interface.
description: |
    Provides for making efficient HTTP/HTTPS requests, providing either a simple or streaming interface.
builddeps  :
    - haskell-aeson-devel
    - haskell-cabal-install
    - haskell-conduit-extra-devel
    - haskell-http-client-tls-devel
rundeps    :
    - devel:
        - haskell-aeson-devel
        - haskell-conduit-extra-devel
        - haskell-http-client-tls-devel
networking : yes
setup      : |
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
