name       : haskell-http-conduit
version    : 2.3.1
release    : 2
source     :
    - http://hackage.haskell.org/package/http-conduit-2.3.1/http-conduit-2.3.1.tar.gz : 8251c3f0ab2a42b998bda4aaf2805e8c3325f0084462502661ce964f671f7859
license    : BSD-3-Clause
component  : programming.haskell
summary    : Provides for making efficient HTTP/HTTPS requests, providing either a simple or streaming interface.
description: |
    Provides for making efficient HTTP/HTTPS requests, providing either a simple or streaming interface.
builddeps  :
    - haskell-aeson
    - haskell-cabal-install
    - haskell-conduit-extra
    - haskell-http-client-tls
networking : yes
setup      : |
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
